In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('weight-height - weight-height.csv')

In [3]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [4]:
df.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x = df[['Height']]
y= df[['Weight']]

In [7]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y , test_size = .30, random_state = 1)

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
reg = LinearRegression()

In [10]:
reg.fit(xtrain, ytrain)

LinearRegression()

In [11]:
reg.score(xtest, ytest)

0.8588721747814503

In [12]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [13]:
mean_squared_error(ytest, reg.predict(xtest))

149.6378737952226

In [14]:
mean_absolute_error(ytest, reg.predict(xtest))

9.79082012333304

In [16]:
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier

In [17]:
KNReg = KNeighborsRegressor()

In [18]:
KNReg.fit(xtrain, ytrain)

KNeighborsRegressor()

In [19]:
KNReg.score(xtest, ytest)

0.8300556993157646

In [20]:
mean_squared_error(ytest, KNReg.predict(xtest))

180.19199104516815

In [21]:
mean_absolute_error(ytest, KNReg.predict(xtest))

10.68002282962836

In [23]:
reg.predict([[70]])

array([[189.94396753]])

In [24]:
KNReg.predict([[70]])

array([[181.98543476]])

In [25]:
xtest.head()

Height
7154  65.068038
3258  70.824643
2188  68.663594
5609  65.987610
3186  70.901461

In [26]:
ytest.head()

Weight
7154  160.800726
3258  184.516688
2188  184.262796
5609  166.844114
3186  200.466282

In [27]:
reg.predict([[65.068038]])

array([[152.16232244]])

In [28]:
KNReg.predict([[65.068038]])

array([[163.93768308]])

In [29]:
from sklearn.preprocessing import LabelEncoder

In [30]:
le = LabelEncoder()

In [53]:
df2 = pd.read_csv('weight-height - weight-height.csv')

In [54]:
df2.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [55]:
df2['Gender'] = le.fit_transform(df[['Gender']])

In [56]:
df2.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [57]:
df2['Gender'].value_counts()

1    5000
0    3555
Name: Gender, dtype: int64

In [58]:
x2 = df2.drop('Gender', axis = 'columns')

In [59]:
x2.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [60]:
y2 = df2[['Gender']]

In [61]:
y2.head()

Gender
0       1
1       1
2       1
3       1
4       1

In [62]:
y2.tail()

Gender
8550       0
8551       0
8552       0
8553       0
8554       0

In [39]:
#x2train, y2train, x2test, y2test = train_test_split(x2, y2, test_size = .30, random_state=1)

In [63]:
KNClf=KNeighborsClassifier(n_neighbors=100)

In [64]:
x2train, x2test, y2train, y2test = train_test_split(x2, y2, test_size = .30, random_state=1)

In [65]:
#KNClf.fit(x2train,y2train)

In [66]:
x2.shape

(8555, 2)

In [67]:
y2.shape

(8555, 1)

In [68]:
KNClf.fit(x2train,y2train)

KNeighborsClassifier(n_neighbors=100)

In [69]:
x2test.head()

Height      Weight
7154  65.068038  160.800726
3258  70.824643  184.516688
2188  68.663594  184.262796
5609  65.987610  166.844114
3186  70.901461  200.466282

In [70]:
y2test.head()

Gender
7154       0
3258       1
2188       1
5609       0
3186       1

In [71]:
KNClf.score(x2test, y2test)

0.9185820023373588

In [73]:
y_pred = KNClf.predict(x2test)

In [75]:
y_pred

array([1, 1, 1, ..., 0, 1, 1], dtype=int64)